# Generated by Django 5.2.3 on 2025-06-19 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp01", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="down",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="board",
            name="filename",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="board",
            name="filesize",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="board",
            name="hit",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="board",
            name="post_date",
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
