# Generated by Django 5.2.1 on 2025-07-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.CharField(max_length=20, null=True)),
                ("title", models.CharField(max_length=500, null=True)),
                ("grade", models.FloatField(null=True)),
                ("custom_count", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
