# Generated by Django 5.2.1 on 2025-07-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app03", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="custom_count",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
