# Generated by Django 5.2 on 2025-07-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                ("password", models.CharField(max_length=100, verbose_name="비밀번호")),
                ("username", models.CharField(max_length=10, verbose_name="글쓴이")),
                (
                    "filename",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="파일명"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="원본파일명"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "게시글",
                "verbose_name_plural": "게시글 목록",
                "db_table": "posts",
            },
        ),
    ]
