# Generated by Django 5.2.3 on 2025-06-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app02", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="filesizw",
            new_name="filesize",
        ),
    ]
